version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rocky_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: rocky
      MYSQL_USER: user_rocky
      MYSQL_PASSWORD: gympass
      TZ: America/Bogota
    ports:
      - "3307:3306"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci"
    ]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "user_rocky", "-pgympass"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

