spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_HOST_PORT}/${DB_NAME}?useSSL=false&serverTimezone=${TZ}&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: true  # en contenedor suele ser mejor cachear; opcional

server:
  port: ${SERVER_PORT}
  error:
    include-message: always

